'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ChevronLeft, ThumbsUp, ThumbsDown, Copy } from 'lucide-react';
import { AiBadge } from '@/components/ai/AiBadge';
import { Citation, SourceList } from '@/components/ai/Citation';
import { AiDisclaimer } from '@/components/ai/AiDisclaimer';
import { cn } from '@/lib/cn';
import { AlertTriangle, Sparkles } from 'lucide-react';
import type { AiSummaryResult } from '@/types/ai';

/** Full AI summary. Every claim carries a citation into the source PDF. */
export function SummaryView({ summary }: { summary: AiSummaryResult }) {
  const router = useRouter();
  const [vote, setVote] = useState<'up' | 'down' | null>(null);

  return (
    <main className="pb-8">
      <header className="flex items-center gap-3 bg-white px-4 py-2">
        <button
          onClick={() => router.back()}
          aria-label="Go back"
          className="flex h-[38px] w-[38px] items-center justify-center rounded-[10px] bg-canvas text-ink"
        >
          <ChevronLeft size={21} strokeWidth={1.75} aria-hidden />
        </button>
        <h1 className="text-card-title font-semibold tracking-[-0.02em]">Tender Summary</h1>
      </header>

      <div className="px-5 pt-3.5">
        {summary.notice && (
          <div
            role="status"
            className="mb-3 flex items-start gap-2.5 rounded-[12px] border border-soon/25 bg-soon-bg px-3 py-2.5"
          >
            <AlertTriangle size={15} strokeWidth={2.1} className="mt-px shrink-0 text-soon" aria-hidden />
            <p className="text-[11.5px] leading-[1.45] text-ink-2">{summary.notice}</p>
          </div>
        )}

        <section className="rounded-lg border border-ai-line bg-white p-4 shadow-card">
          <div className="mb-3 flex items-center justify-between">
            <AiBadge label="AI Summary" />
            <span className="text-micro text-ink-3">From {summary.citations.length} {summary.citations.length === 1 ? 'source' : 'sources'}</span>
          </div>

          <p className="text-body text-ink">{summary.overview}</p>

          <div className="mt-3 border-t border-line pt-3">
            <h2 className="mb-1 text-micro font-semibold uppercase tracking-[0.07em] text-ink-3">Key points</h2>
            <ul>
              {summary.keyPoints.map((p, i) => (
                <li key={i} className="mt-2.5 flex gap-2.5">
                  <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-ai" aria-hidden />
                  <span className="flex-1 text-[13.5px] leading-5 text-ink-2">
                    {p.text}
                    {p.citationIndex && <Citation index={p.citationIndex} />}
                  </span>
                </li>
              ))}
            </ul>
          </div>

          <div className="mt-3 flex items-center justify-between border-t border-line pt-3">
            <div className="flex items-center gap-2">
              <span className="text-[11.5px] text-ink-3">Helpful?</span>
              {(['up', 'down'] as const).map((v) => {
                const Icon = v === 'up' ? ThumbsUp : ThumbsDown;
                return (
                  <button
                    key={v}
                    onClick={() => setVote(v)}
                    aria-label={v === 'up' ? 'Mark summary helpful' : 'Mark summary unhelpful'}
                    aria-pressed={vote === v}
                    className={cn(
                      'flex h-7 w-7 items-center justify-center rounded-lg',
                      vote === v ? 'bg-ai-bg text-ai' : 'bg-canvas text-ink-2',
                    )}
                  >
                    <Icon size={15} strokeWidth={2} aria-hidden />
                  </button>
                );
              })}
            </div>
            <button className="flex items-center gap-1.5 text-caption font-semibold text-ai">
              <Copy size={14} strokeWidth={2} aria-hidden />
              Copy
            </button>
          </div>
        </section>

        {summary.citations.length > 0 && (
          <>
            <h2 className="mb-2 mt-4 text-micro font-semibold uppercase tracking-[0.07em] text-ink-3">
              Sources
            </h2>
            <SourceList citations={summary.citations} />
          </>
        )}

        <p className="mt-3 flex items-center justify-center gap-1.5 text-[11px] text-ink-3">
          <Sparkles size={11} strokeWidth={2} aria-hidden />
          {summary.source === 'groq'
            ? `Generated by ${summary.model} via GroqCloud from the tender documents`
            : summary.source === 'mock'
              ? 'Sample summary — no API key configured'
              : 'Generated from listing metadata'}
        </p>

        <div className="mt-3.5">
          <AiDisclaimer />
        </div>
      </div>
    </main>
  );
}
