'use client';
import { useRouter } from 'next/navigation';
import { ChevronLeft, AlertTriangle } from 'lucide-react';
import { AiBadge } from '@/components/ai/AiBadge';
import { Citation } from '@/components/ai/Citation';
import { AiDisclaimer } from '@/components/ai/AiDisclaimer';
import { cn } from '@/lib/cn';
import { Sparkles } from 'lucide-react';
import type { AiMatchResult } from '@/types/ai';

/** Score colour is a quality signal, not a tender status. */
function toneFor(score: number) {
  if (score >= 80) return { bar: 'bg-open', text: 'text-open' };
  if (score >= 60) return { bar: 'bg-soon', text: 'text-soon' };
  return { bar: 'bg-urgent', text: 'text-urgent' };
}

export function MatchView({ match }: { match: AiMatchResult }) {
  const router = useRouter();
  const { score, factors, warnings } = match;
  const circumference = 2 * Math.PI * 33;

  return (
    <main className="pb-8">
      <header className="flex items-center gap-3 bg-white px-4 py-2">
        <button
          onClick={() => router.back()}
          aria-label="Go back"
          className="flex h-[38px] w-[38px] items-center justify-center rounded-[10px] bg-canvas text-ink"
        >
          <ChevronLeft size={21} strokeWidth={1.75} aria-hidden />
        </button>
        <h1 className="text-card-title font-semibold tracking-[-0.02em]">Why this tender?</h1>
      </header>

      <div className="px-5 pt-3.5">
        <section className="flex items-center gap-3.5 rounded-lg border border-ai-line bg-white p-4 shadow-card">
          <svg width="76" height="76" viewBox="0 0 80 80" role="img" aria-label={`${score} percent match`}>
            <circle cx="40" cy="40" r="33" stroke="#EDF1F6" strokeWidth="8" fill="none" />
            <circle
              cx="40" cy="40" r="33" stroke="#12805C" strokeWidth="8" fill="none" strokeLinecap="round"
              strokeDasharray={circumference}
              strokeDashoffset={circumference * (1 - score / 100)}
              transform="rotate(-90 40 40)"
            />
            <text x="40" y="43" textAnchor="middle" fontSize="21" fontWeight="700" fill="#1B2430">{score}</text>
            <text x="40" y="55" textAnchor="middle" fontSize="9" fontWeight="600" fill="#7C8798">MATCH</text>
          </svg>
          <div className="min-w-0 flex-1">
            <AiBadge label="AI Match" className="mb-1.5" />
            <p className="text-body-lg font-semibold tracking-[-0.02em]">Strong match for your profile</p>
            <p className="mt-1 text-caption leading-[18px] text-ink-2">
              Based on your categories, province, past saves and company compliance.
            </p>
          </div>
        </section>

        <section className="mt-3.5 rounded-lg border border-line bg-white p-4">
          <h2 className="text-body-lg font-semibold tracking-[-0.02em]">Score breakdown</h2>
          {factors.map((f) => {
            const tone = toneFor(f.score);
            return (
              <div key={f.key} className="mt-3">
                <div className="mb-1.5 flex items-baseline justify-between">
                  <span className="text-meta font-medium text-ink">{f.label}</span>
                  <span className={cn('text-caption font-semibold', tone.text)}>{f.note}</span>
                </div>
                <div className="h-1.5 overflow-hidden rounded-full bg-[#EDF1F6]">
                  <div className={cn('h-full rounded-full', tone.bar)} style={{ width: `${f.score}%` }} />
                </div>
              </div>
            );
          })}
        </section>

        {warnings.length > 0 && (
          <section className="mt-3.5 rounded-lg border border-line bg-white p-4">
            <h2 className="flex items-center gap-2 text-body-lg font-semibold tracking-[-0.02em]">
              <AlertTriangle size={17} strokeWidth={2} className="text-soon" aria-hidden />
              Before you bid
            </h2>
            {warnings.map((w, i) => (
              <p key={i} className="mt-2 text-meta leading-5 text-ink-2">
                {w.text}
                {w.citationIndex && <Citation index={w.citationIndex} />}
              </p>
            ))}
          </section>
        )}

        <div className="mt-3.5">
          <AiDisclaimer>
            The score is calculated from a fixed rubric against your profile — not generated by a language
            model. It is a guide, not a guarantee of eligibility or award.
          </AiDisclaimer>
        </div>

        {match.source === 'gemini' && (
          <p className="mt-3 flex items-center justify-center gap-1.5 text-center text-[11px] text-ink-3">
            <Sparkles size={11} strokeWidth={2} aria-hidden />
            Requirements extracted from the tender documents by {match.model}
          </p>
        )}
      </div>
    </main>
  );
}
